name: Test unitaire de l'app
on: push 
env: 
  APP_VERSION: "1.0.0"
jobs: 
  Tests-app:
    runs-on: ubuntu-latest
    steps:
      - name: J'effectue des tests 
        id: test
        run: echo "Salut"
  
  Build-app: 
    needs: Tests-app
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du répo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-qemu-action@v1
      - name: Installation de Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login au docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push docker
        uses: docker/build-push-action@v2
        with:
          context: . 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/imagination:${{ env.APP_VERSION }}